# Generated by Django 2.0.4 on 2018-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
