# Generated by Django 2.0.4 on 2018-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0002_auto_20180427_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='snuser',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
