# Generated by Django 2.0.4 on 2018-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0005_auto_20180428_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/670.png', upload_to=''),
        ),
    ]
