# Generated by Django 2.0.4 on 2018-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0006_auto_20180428_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
