# Generated by Django 2.0.4 on 2018-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0007_auto_20180428_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.jpg', null=True, upload_to=''),
        ),
    ]
