# Generated by Django 2.0.4 on 2018-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0008_auto_20180428_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(default='../media/anonymous.jpg', null=True, upload_to=''),
        ),
    ]
