# Generated by Django 2.0.4 on 2018-04-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0009_auto_20180428_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_user_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='SN.Post'),
        ),
    ]
