# Generated by Django 2.0.4 on 2018-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0010_auto_20180430_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
